### ISSUE TITLE
Apv2 patch applied but Game still stuck at protection screen

### ISSUE THREAD

**Issue by Ninten2** [alex-free/aprip#2]
I've been trying to patch Winning Eleven 2002 [J] [SLPM-87056] (it's a late 2000 game so it has Apv2 protection), I used Aprip to patch the track1 of the game, the app said that found Apv2 and applied succesfully the bypass. However after I burn the game on a CD-R and boot it on my PSOne it still gets stuck in the protection screen.

[https://imgur.com/QGqUANv](url)

[https://imgur.com/XyKhq4f](url)

First image is the Aprip, second one is the game stuck in the protection. 
Maybe I'm missing something, but not sure.

**Comment by alex-free** [comment]
img links are broken, but I looked at this game and it applies the VC0 patch. Does the console have a non-stealth mod-chip? The VC0 patch should work for consoles without a mod-chip. I'm gonna check this out more @Ninten2 .

**Comment by alex-free** [comment]
Confirmed patch seems to work in emulation, will try on a real console next:
![Screenshot from 2024-07-06 23-01-33](https://github.com/alex-free/aprip/assets/72545918/970a4439-a340-489e-91a9-b50e70536350)

**Comment by alex-free** [comment]
I checked with a console without any mod-chip using Tonyhax International and the bypass does work. The VC0 bypass generated by Aprip doesn't work for consoles with a non-stealth mod-chip (I also have a chipped console and verified this, but I already knew it wouldn't work).

Aprip can sometimes generate a Fake PAL bypass that does also work for non-stealth mod-chips, but it can't for this game.

I can add support for the game in Tonyhax International (so that it also works for non-stealth mod-chip consoles)

**Comment by alex-free** [comment]
Closing due to lack of response.
